version: '3.9'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ../:/app
      - ../../node-rockstar-api/:/opt/node-rockstar-api
    command: /bin/sh -c "while sleep 100; do :; done"
